travis:
  secure:
    BINSTAR_TOKEN: D5sPp9gS7poTsPkL5f4Amk4kPxCZmSEcgvLltLolnZRGgP1FSfHtn2t3rqDmTA4FInhhvxbXaj8RRpaVh+FnKxg96Cn2KmLr5rClBjoVWyWAj8M0pQIesUMIAgOO9aQ7NGc7oYmY7PEPPBhVi8KcXoHhN3mQJyk2H2d8tklMQhOL+kh9Wwce50v1TiwIGP9BPPd65knN9iVZ8QddirZEEWSzZF+k2WApSOVKrwmwq7YLg+/mziQeo8+r971q4NbQJUY6qlXR0airZwwXGCXYZSkRp4S4ZkCMqg/+SkSi4nfNZQq4OSnoUBa6CFdZIuo86phQTKNMzLG+vyjW7l1eGkslFmeGoeXQ6NQYlYxdlnvs0tR+i858HmgMxkTWL3ouxIjKqlab08Ut0CdLszWy7MDz6Ye4lNQCIl4SAAO7K4qBK+QIUCpOynTFPSLMdBfalsfYVSwxIkQOijdf/inZvL7BbOBcOKtdTy0mNikONjD1VqZYwQThmGnoQc1deIUXsOz9b8XO2gKviVGOXtYgGyDngE9RyQSRQIadXbYshPElRjKovUc3sO8ronkngDzT8VXApHeaVNPrGEvxlreXbyze0nLUTTYLoi8/eP2lnJLoTO5IBuGpS9Ytu13ktMFJWMcqcsDndVvKVn9YVJEH74J3+Qsr/0pDvD2G+GdJi80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
