travis:
  secure:
    BINSTAR_TOKEN: D95SKeCZ31pk41xJbm5QG14tG9OdPg+twl8vWoLkMev0JZ5LLdHGiLNHWU2ECpyhCF9o1at3v8ajKP9aVlbfy7r9jZpWP4tINKFUTLn2tfUBnE59dODoDYYI4Sfs4T71xcs44Z+exE8fPUtlgmQvs51vxzsqbQhNTTNrNYekxQpI5NW4g+RP8pQl0avGU6SB73V8iTuQOixFbqmwz3uhcGvbRkvp+2MXwNjy6yJMT7Zh9Pkegai/+yN9MPAilsQ4LjB6NwJVNf+5zUocOMYLBRsvaRJRUp9GMlUNv5/3lljzGzmQKJqADSrhhfqH66BjP2F9DgQAOXJ+7sH6L8kafomYBKQqKpAD+6FpygqMoT72nInXG2hYveYwhv7I3Kc/awpGWU+S+ATwBiHL4nJaMdLxTkonl2B4mSGa+cWam8CRneQJCbhdX7NypHLBOIAtJ9z5oVkLwbSgNGJNGb2DOFHu1sx893g0IDnW1/XqGIF+ZhiHc8Cm9/HNKNCQ4M/cCDbnE7G+lohNz2EDo0zbqPo4f2Nwjp/qpLgfyuVOi2khzk0EXf2nD/4SMeFfOltFPlJ7NW5MPypU8SWhBC8/5MHVBs39Qg3duRHkPBpGMbEReTyB1ZKLykXBed4TJQUc/xcFwt/GutzeyOlZ9CshBlCbAAjttSk3lr4UN4wzSyU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
